f = open("test.txt", "w")
f.write("I am a test file.\n")
f.write("Maybe someday, he will promote me to a real file.\n")
f.write("Man, I long to be a real file\n")
f.write("and hang out with all my new real file friends.\n")
f.close()
